version: "3.8"

services:

  db:
    image: postgres:16.2
    container_name: local-postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=rootpwd
      - POSTGRES_USER=admin
      - POSTGRES_DB=qrcode_gen
    # volumes:
    #   - ~/apps/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  localstack:
    image: localstack/localstack:2.0.0
    container_name: localstack
    ports:
      - "4566:4566" # LocalStack main port
      - "4571:4571" # LocalStack S3 port
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
    # networks:
    #   - localstack_network
