version: "3.8"

services:

  db:
    image: postgres:16.2
    container_name: local-postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=rootpwd
      - POSTGRES_USER=admin
      - POSTGRES_DB=qrcode_gen
    # volumes:
    #   - ~/apps/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
