version: "3.1"

services:

  mysql:
    image: mysql:8.3.0
    container_name: local-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=MyTempPass#123
    volumes:
      - ./db:/docker-entrypoint-initdb.d/ # SQL full dump file
    ports:
      - "3306:3306"

  redis:
    image: redis:7.2.4
    container_name: local-redis
    ports:
      - "6379:6379"
