version: "3"

services:
  bookstore-backend:
    build:
      context: ./book_store_backend
      dockerfile: Dockerfile
    container_name: bookstore-server
    restart: always
    ports:
      - "8000:8080"

  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/jenkins_home
      - ./book_store_backend/src:/var/jenkins/code
