CREATE DATABASE IF NOT EXISTS spendsmart;

USE spendsmart;

CREATE TABLE IF NOT EXISTS USER (
    ID VARCHAR(50) PRIMARY KEY,
    USERNAME VARCHAR(100),
    PASSWORD VARCHAR(100)
);

INSERT INTO USER (ID, USERNAME, PASSWORD)
SELECT UUID(), 'temp_user', '$2a$04$4xemeBbVefN3OGfb48qd5.W/5liA7AVCnqyZS6CN4SoSEEdmJnAom'
WHERE NOT EXISTS (SELECT 1 FROM USER);