CREATE DATABASE IF NOT EXISTS spendsmart;

CREATE TABLE IF NOT EXISTS USER (
    ID VARCHAR(36) DEFAULT UUID() PRIMARY KEY,
    USERNAME VARCHAR(50),
    PASSWORD VARCHAR(50),
);

INSERT INTO USER (USERNAME, PASSWORD)
SELECT 'temp_user', '$2a$04$4xemeBbVefN3OGfb48qd5.W/5liA7AVCnqyZS6CN4SoSEEdmJnAom'
WHERE NOT EXISTS (SELECT 1 FROM USER);